### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by AngelOnFira** [longfangsong/anatole-zola#1]
Hey! I like this theme a lot, and I'm considering using it on a project. However, there is no license on the repo, and therefore it has ambiguous copyright for others to use. I was wondering if you could add one that represents your intentions for others to use. Thanks!

**Comment by longfangsong** [comment]
Thank you for your remind. I add the license file in #2.
It's The Unlicese, feel free to use this in any way you can imagine!
