### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by peileiscott** [longfangsong/anatole-zola#12]
Hi, longfangsong. This theme is amazing and I wanna use it for my blog website. However, seems like this theme does not support dark mode, could you please consider adding this feature?

**Comment by longfangsong** [comment]
> Hi, longfangsong. This theme is amazing and I wanna use it for my blog website. However, seems like this theme does not support dark mode, could you please consider adding this feature?

Dark mode is a good idea! Personally I want it too. Though [the origin farbox theme](https://github.com/hi-caicai/farbox-theme-Anatole) doesn't have one, maybe I can learn from [the hugo version](https://github.com/lxndrblz/anatole).

**Comment by longfangsong** [comment]
I added basic support of dark mode in 1f226ed you may reference the readme and have a try now!
